"""Aggregate household sector — singleton per Nation.

In C++ the household sector is implicit: demand (D2) emerges from the income
generated by wages and government transfers (ALLOC / PROFIT functions). There
is no explicit C++ struct for households in the single-household-type baseline.

This class holds the aggregate state needed by:
  - ALLOC (Task 1.11): distribute household income across consumption-good firms
  - PROFIT (Task 1.11): receive dividend income
  - MACRO (Task 1.12): confirm income-expenditure identity

In v3, heterogeneous Household agents are a Milestone-10 extension. Until then,
HouseholdSector is a plain aggregate class, not an AgentSet.
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dsk.nation import Nation
    from dsk.parameters.global_parameters import GlobalParameters
    from dsk.parameters.nation_parameters import NationParameters


class HouseholdSector:
    """Aggregate household sector. Receives wage and unemployment income; allocates to consumption."""

    def __init__(self, nation: "Nation") -> None:
        self.nation = nation

        # --- Income flows (computed each period by MACRO / PROFIT) ---
        # Total wage income received by employed households
        self.wage_income: float = 0.0
        # Total unemployment benefits received (= wu * w * U * LS)
        self.unemployment_income: float = 0.0
        # Dividend income from firm/bank holdings (not in KS10 baseline; = 0)
        self.dividend_income: float = 0.0
        # Aggregate household income = wage_income + unemployment_income + dividend_income
        self.income: float = 0.0

        # --- Expenditure ---
        # Nominal consumption expenditure this period (= income in baseline, no saving)
        self.consumption_budget: float = 0.0
        # Realised nominal consumption (after allocation across s2 firms)
        self.realised_consumption: float = 0.0

        # --- Savings ---
        # Net household savings (= income - consumption; = 0 in baseline)
        self.savings: float = 0.0

        # --- Consumption parameters ---
        # unemployment_benefit_share: wu — fraction of wage paid as unemployment benefit
        # (stored here for convenience; canonical value is in NationParameters)
        self.unemployment_benefit_share: float = 0.4

    # ------------------------------------------------------------------

    def initialise_from_parameters(
        self,
        gparams: "GlobalParameters",
        nparams: "NationParameters",
    ) -> None:
        """Set household initial state.

        In C++ INITIALIZE, the household sector has no explicit zero-initialisation
        block — aggregate income is a derived quantity computed each period (MACRO,
        ALLOC). This method sets all Python state to pre-production zeros and
        caches the unemployment_benefit_share parameter.
        """
        self.unemployment_benefit_share = nparams.unemployment_benefit_share  # wu = 0.4

        # All income/expenditure flows are 0 before the first production step
        self.wage_income = 0.0
        self.unemployment_income = 0.0
        self.dividend_income = 0.0
        self.income = 0.0
        self.consumption_budget = 0.0
        self.realised_consumption = 0.0
        self.savings = 0.0

        # Carried-forward unmet real demand (Cpast in C++); 0 at init
        self.unmet_real_demand_prev: float = 0.0

    # ------------------------------------------------------------------
    # ALLOC — distribute real consumption budget across sector-2 firms
    # ------------------------------------------------------------------

    def allocate_consumption(
        self,
        market_shares: list,
        prices: list,
        firms: list,
        cons_nominal: float,
        cpi: float,
        max_iterations: int = 1000,
    ) -> float:
        """Iteratively allocate real consumption demand across sector-2 firms.

        Ports C++ dsk_main.cpp ALLOC() lines 5580-5640.

        Algorithm:
          Cres = Cons / cpi                                  (real budget)
          ftot = sum(f2(1,j))                                (normaliser)
          Q2temp(j) = Q2(1,j) + N(2,j)                       (per-firm supply)
          while Cres >= 1 and ftot > 0:
            for j with f_temp2(j) > 0:
              D_temp2(j) = Cres * f_temp2(j)
              if n==1: D2(1,j) += D_temp2(j)
              if D_temp2(j) <= Q2temp(j):                    (firm meets demand)
                if n>1: D2(1,j) += D_temp2(j)
                Cresbis -= D_temp2(j); Q2temp(j) -= D_temp2(j)
                if n==1: l2(j) = 1
              else:                                          (firm rations)
                if n>1: D2(1,j) += Q2temp(j)
                Cresbis -= Q2temp(j); f_temp2(j) = 0
                if n==1: l2(j) = 1 + D_temp2(j) - Q2temp(j)
                Q2temp(j) = 0
            renormalise f_temp2; Cres = Cresbis; n++
          Cpast = Cres                                       (unmet real demand)

        After completion: each firm has updated `demand` (D2(1,j)) and
        `unfilled_demand` (l2(j)).

        Parameters
        ----------
        market_shares
            Per-firm market share array (f2(1,j)) in same order as `firms`.
        prices
            Per-firm price array (p2(1,j)) — not used in allocation itself, but
            passed for symmetry with the IMPLEMENTATION_PLAN signature.
        firms
            List of ConsumptionGoodFirm to mutate.
        cons_nominal
            Nominal consumption budget Cons (= w*LD + Divtot_prev + G).
        cpi
            Current-period CPI (= sum p2*f2).
        max_iterations
            Safety cap on the while-loop; the C++ runs to convergence.

        Returns
        -------
        float
            Cpast — unmet real consumption demand carried out of the loop
            (forced household saving under baseline flagCN=0).
        """
        n_firms = len(firms)
        if n_firms == 0 or cpi <= 0.0:
            return 0.0

        # Reset per-firm demand and unfilled-demand storage
        f_temp = list(market_shares)        # working copy of f2(1,j)
        d2 = [0.0] * n_firms                # cumulated D2(1,j)
        l2 = [0.0] * n_firms                # l2(j) — set on first pass only
        q2temp = [
            firms[j].production + firms[j].inventory for j in range(n_firms)
        ]                                    # Q2(1,j) + N(2,j) — opening supply

        Cres = cons_nominal / cpi           # real budget
        ftot = sum(f_temp)
        n_iter = 1

        while Cres >= 1.0 and ftot > 0.0 and n_iter <= max_iterations:
            Cresbis = Cres
            for j in range(n_firms):
                f_j = f_temp[j]
                if f_j <= 0.0:
                    continue

                d_temp = Cres * f_j

                if n_iter == 1:
                    d2[j] += d_temp

                if d_temp <= q2temp[j]:
                    if n_iter > 1:
                        d2[j] += d_temp
                    Cresbis -= d_temp
                    q2temp[j] -= d_temp
                    if n_iter == 1:
                        l2[j] = 1.0
                else:
                    if n_iter > 1:
                        d2[j] += q2temp[j]
                    Cresbis -= q2temp[j]
                    f_temp[j] = 0.0
                    if n_iter == 1:
                        # C++ line 5629: l2(j) = 1 + D_temp(j) - Q2temp(j)
                        l2[j] = 1.0 + d_temp - q2temp[j]
                    q2temp[j] = 0.0

            ftot = sum(f_temp)
            if ftot > 0.0:
                inv = 1.0 / ftot
                f_temp = [x * inv for x in f_temp]
            Cres = Cresbis
            n_iter += 1

        # Cpast = leftover unmet real demand (forced household saving in baseline)
        Cpast = max(0.0, Cres)
        self.unmet_real_demand_prev = Cpast

        # Push results onto firms
        for j, firm in enumerate(firms):
            firm.demand = d2[j]
            firm.unfilled_demand = l2[j]

        # Track realised nominal consumption (= sum p2 * actual_consumption)
        self.realised_consumption = 0.0
        for j, firm in enumerate(firms):
            actual = min(firm.demand, firm.production + firm.inventory)
            self.realised_consumption += firm.price * actual

        # Bookkeeping
        self.consumption_budget = cons_nominal

        return Cpast
